name: Sync to personal repo on PR merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add remote for personal repo
        run: |
          git remote add personal https://x-access-token:${{ secrets.SYNC_TO_PERSONAL_REPO }}@github.com/KimDongGyun23/Hanzipmari.git

      - name: Push main to personal
        run: |
          # 현재 main 체크아웃 보장
          git checkout main
          git push personal main --force

      - name: Create export branch without workflows
        run: |
          git checkout -b export-for-personal
          git rm -r --cached .github || true
          git commit -m "chore: exclude .github for personal mirror" || true

      - name: Push to personal main
        run: |
          git push personal export-for-personal:main --force
